### ISSUE TITLE
Issues with `preprocess_spm_calcs` method.

### ISSUE THREAD

**Issue by yakutovicha** [eimrek/mc-empa-scanning-probe#29]
- The work chain names are too generic, I had issues when running `PdosWorkChain` by the QE app. We should come up with better search criteria.
- This line is wrong, it only works if `n.outputs` gives no outputs:
https://github.com/nanotech-empa/aiidalab-empa-scanning-probe/blob/2cb0f88666ba3d429b7cb23874fd4a0f5814fb3d/common.py#L240

**Comment by eimrek** [comment]
Hi @yakutovicha

1) I agree

2) Could you elaborate a bit? Are you saying that it's not detecting the `WITHSCHEDULER` state correctly and the underway workchain is not skipped?

**Comment by yakutovicha** [comment]
> 2\. Could you elaborate a bit?

sure.

> Are you saying that it's not detecting the `WITHSCHEDULER` state correctly and the underway workchain is not skipped?

The fact that the process is still running is detected earlier, and that part works:
https://github.com/nanotech-empa/aiidalab-empa-scanning-probe/blob/2cb0f88666ba3d429b7cb23874fd4a0f5814fb3d/common.py#L237-L239

The issue is with the `out`. According to the current code, it is supposed to be an object, but it is actually a `string`. So if the process has outputs, the `out.get_state()` call fails.

**Comment by yakutovicha** [comment]
After the app was embedded into the "surfaces" app, the issue had been fixed there.
